version: '3'
services:
  web:
    image: littlekidogo/qb:staging
    env_file:
      - web.env
    ports:
      - "9032:9032"
    links:
      - db
  db:
    image: postgres:latest
    env_file:
      - db.env
    ports:
      - "5433:5432"
    volumes:
      - qb-staging:/var/lib/postgresql
volumes:
  qb-staging:
    external: true
